name: Build
on:
  push:
    branches: [ master_java_2.0 ]
  pull_request:
    branches: [ master_java_2.0 ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IM_BASE_URI: ${{ env.IM_BASE_URI }}
      IM_APPKEY: ${{ env.IM_APPKEY }}
      IM_CLIENT_ID: ${{ env.IM_CLIENT_ID }}
      IM_CLIENT_SECRET: ${{ env.IM_CLIENT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven
        run: mvn --batch-mode -Pci clean package
      - name: Maven Test
        run: mvn test

